apiVersion: v1
kind: Service
metadata:
  name: javascript-test
  namespace: express-test
spec:
  type: LoadBalancer
  selector:
    app: javascript-test
  ports:
    - protocol: TCP
      port: 1313
      targetPort: 1313